# gui_constants.py

# Button visibility
BTN_INVISIBILITY = True

# Sidebar button distance
SIDEBAR_BUTTON_DISTANCE = 100

# Slider configuration
SLIDER_COORDINATES = (660, 960)  # (x, y) position for the slider
SLIDER_SIZE = (1000, 30)         # (width, height) of the slider
IMG_SLIDER_DROP_SHADOW_COORDINATES = (632, 973)

# Text Coordinates
TXT_TITLE_COORDINATES = (150, 25)
TXT_SIDEBAR_TEXT_HOME = (175,140)
TXT_SIDEBAR_TEXT_GRAPHS = (175,140 + SIDEBAR_BUTTON_DISTANCE)

TXT_SLIDER_VALUE_COORDINATES = (1159, 992)
SLIDER_MIN_MAX_Y = 992
TXT_SLIDER_MIN_COORDINATES = (638, SLIDER_MIN_MAX_Y)
TXT_SLIDER_MAX_COORDINATES = (1700, SLIDER_MIN_MAX_Y)
SLIDER_PLUSMINUS_Y = 992
TXT_SLIDER_MINUS_COORDINATES = (685, SLIDER_PLUSMINUS_Y)
TXT_SLIDER_PLUS_COORDINATES = (1631, SLIDER_PLUSMINUS_Y)

# Pot Names
TXT_POT_NAMES_Y = 170
TXT_POT_NAMES_BK_COORDINATES = (725, TXT_POT_NAMES_Y)
TXT_POT_NAMES_MLT_COORDINATES = (1164, TXT_POT_NAMES_Y)
TXT_POT_NAMES_HLT_COORDINATES = (1593, TXT_POT_NAMES_Y)

# Pump Names and Values
PUMP_NAME_Y = 870
TXT_P1_COORDINATES = (947, PUMP_NAME_Y)
TXT_P2_COORDINATES = (1593, PUMP_NAME_Y)
PUMP_VALUE_Y = 785
TXT_P1_VALUE_COORDINATES = (945, PUMP_VALUE_Y)
TXT_P2_VALUE_COORDINATES = (1593, PUMP_VALUE_Y)

# REG Labels
REG_NAME_Y = 324
TXT_REG_BK_COORDINATES = (550, REG_NAME_Y)
TXT_REG_HLT_COORDINATES = (1768, REG_NAME_Y)
REG_VALUE_Y = 390
TXT_REG_BK_VALUE_COORDINATES = (554, REG_VALUE_Y)
TXT_REG_HLT_VALUE_COORDINATES = (1773, REG_VALUE_Y)

# Temperature & Labels
TEMP_Y = 270
TXT_TEMP_BK_COORDINATES = (732, TEMP_Y)
TXT_TEMP_MLT_COORDINATES = (1172, TEMP_Y)
TXT_TEMP_HLT_COORDINATES = (1601, TEMP_Y)

# Efficiency Labels
EFFICIENCY_Y = 320
TXT_EFFICIENCY_BK_COORDINATES = (TXT_TEMP_BK_COORDINATES[0], EFFICIENCY_Y)
TXT_EFFICIENCY_HLT_COORDINATES = (TXT_TEMP_HLT_COORDINATES[0], EFFICIENCY_Y)

# Selection Text
BK_HLT_SELECTED_Y = 136
TXT_BK_SELECTED_COORDINATES = (683, BK_HLT_SELECTED_Y)
TXT_HLT_SELECTED_COORDINATES = (1528, BK_HLT_SELECTED_Y)
PUMP_SELECTED_Y = 851
TXT_P1_SELECTED_COORDINATES = (903, PUMP_SELECTED_Y)
TXT_P2_SELECTED_COORDINATES = (1552, PUMP_SELECTED_Y)
REG_SELECTED_Y = 307
TXT_REGBK_SELECTED_COORDINATES = (510, REG_SELECTED_Y)
TXT_REGHLT_SELECTED_COORDINATES = (1729, REG_SELECTED_Y)

# Font Sizes
TXT_TITLE_SIZE = 25
TXT_SIDEBAR_TEXT_SIZE = 20
TXT_POT_NAMES_SIZE = 32
TXT_SLIDER_VALUE_SIZE = 25
TXT_SLIDER_MINMAX_SIZE = 25
TXT_SLIDER_PLUSMINUS = 20
TXT_REG_SIZE = 20
TXT_REG_VALUE_SIZE = 25
TXT_POT_TEMPERATURES_SIZE = 40
TXT_POT_EFFICIENCY_SIZE = 25
TXT_PUMP_SPEED_SIZE = 40

# IMG GUI Coordinates
IMG_DROPSHADOWS_COORDINATES = (-15, -70)
IMG_SIDEBAR_ACTIVE_BUTTON = (0, 89)
IMG_SIDEBAR_ACTIVE_BUTTON_GRAPHS = (0, 189)
IMG_SIDEBAR_ICON_HOME = (43, 113)

IMG_SIDEBAR_GRAPHS_BUTTON = (0, 89+ SIDEBAR_BUTTON_DISTANCE)
IMG_SIDEBAR_ICON_GRAPHS = (43, 113 + SIDEBAR_BUTTON_DISTANCE)
IMG_KONFUS_LOGO = (70, 445)

IMG_POT_BK_COORDINATES = (598, 209)
IMG_POT_MLT_COORDINATES = (1037, 209)
IMG_POT_HLT_COORDINATES = (1466, 209)
IMG_PIPES_COORDINATES = (723, 264)
IMG_REG_BOX_BK_COORDINATES = (498, 354)
IMG_REG_BOX_HLT_COORDINATES = (1716, 354)
IMG_COIL_COORDINATES = (1466, 366)
IMG_HEATING_ELEMENT_BK_COORDINATES = (600, 509)
IMG_HEATING_ELEMENT_HLT_COORDINATES = (1470, 509)
IMG_PUMP_BOX_P1_COORDINATES = (854, 736)
IMG_PUMP_BOX_P2_COORDINATES = (1503, 736)
IMG_POT_BK_SELECTION_COORDINATES = (585, 195)
IMG_POT_HLT_SELECTION_COORDINATES = (1452, 195)
IMG_P1_SELECTION_COORDINATES = (840, 723)
IMG_P2_SELECTION_COORDINATES = (1490, 723)

# Button Sizes
BTN_POT_ON_OFF = (251, 355)
BTN_PUMP_ON_OFF = (182, 99)
BTN_REG_MARGIN = 15
BTN_REG_ON_OFF = (105+BTN_REG_MARGIN, 69+(BTN_REG_MARGIN*2))
BTN_SIDEBAR_MENU = (399, 100)

# Button Coordinates
BTN_REG_ON_OFF_BK_COORDINATES = (IMG_REG_BOX_BK_COORDINATES[0] - BTN_REG_MARGIN, IMG_REG_BOX_BK_COORDINATES[1] - BTN_REG_MARGIN)
BTN_REG_ON_OFF_HLT_COORDINATES = (IMG_REG_BOX_HLT_COORDINATES[0], IMG_REG_BOX_HLT_COORDINATES[1] - BTN_REG_MARGIN)



