# gui_constants.py

# Sidebar button distance
SIDEBAR_BUTTON_DISTANCE = 100

# Slider configuration
SLIDER_COORDINATES = (660, 960)  # (x, y) position for the slider
SLIDER_SIZE = (1000, 30)         # (width, height) of the slider
IMG_SLIDER_DROP_SHADOW_COORDINATES = (632, 973)

# Text Coordinates
TXT_TITLE_COORDINATES = (150, 25)
TXT_SIDEBAR_TEXT_HOME = (175,140)
TXT_SIDEBAR_TEXT_GRAPHS = (TXT_SIDEBAR_TEXT_HOME[0],TXT_SIDEBAR_TEXT_HOME[1] + SIDEBAR_BUTTON_DISTANCE)
TXT_SIDEBAR_TEXT_SETTINGS = (TXT_SIDEBAR_TEXT_HOME[0],TXT_SIDEBAR_TEXT_HOME[1] + SIDEBAR_BUTTON_DISTANCE*2)

TXT_SLIDER_VALUE_COORDINATES = (1159, 992)
SLIDER_MIN_MAX_Y = 992
TXT_SLIDER_MIN_COORDINATES = (638, SLIDER_MIN_MAX_Y)
TXT_SLIDER_MAX_COORDINATES = (1700, SLIDER_MIN_MAX_Y)
SLIDER_PLUSMINUS_Y = 992
TXT_SLIDER_MINUS_COORDINATES = (685, SLIDER_PLUSMINUS_Y)
TXT_SLIDER_PLUS_COORDINATES = (1631, SLIDER_PLUSMINUS_Y)

TXT_EXIT_COORDINATES = (200, 1050)

# Pot Names Coordinates
TXT_POT_NAMES_Y = 170
TXT_POT_NAMES_BK_COORDINATES = (725, TXT_POT_NAMES_Y)
TXT_POT_NAMES_MLT_COORDINATES = (1164, TXT_POT_NAMES_Y)
TXT_POT_NAMES_HLT_COORDINATES = (1593, TXT_POT_NAMES_Y)

# Pump Names and Values Coordinates
PUMP_NAME_Y = 870
TXT_P1_COORDINATES = (947, PUMP_NAME_Y)
TXT_P2_COORDINATES = (1593, PUMP_NAME_Y)
PUMP_VALUE_Y = 785
TXT_P1_VALUE_COORDINATES = (945, PUMP_VALUE_Y)
TXT_P2_VALUE_COORDINATES = (1593, PUMP_VALUE_Y)

# REG Labels Coordinates
REG_NAME_Y = 324
TXT_REG_BK_COORDINATES = (550, REG_NAME_Y)
TXT_REG_HLT_COORDINATES = (1768, REG_NAME_Y)
REG_VALUE_Y = 390
TXT_REG_BK_VALUE_COORDINATES = (554, REG_VALUE_Y)
TXT_REG_HLT_VALUE_COORDINATES = (1773, REG_VALUE_Y)

# Temperature & Labels Coordinates
TEMP_Y = 270
TXT_TEMP_BK_COORDINATES = (732, TEMP_Y)
TXT_TEMP_MLT_COORDINATES = (1172, TEMP_Y)
TXT_TEMP_HLT_COORDINATES = (1601, TEMP_Y)

# Efficiency Labels Coordinates
EFFICIENCY_Y = 330
TXT_EFFICIENCY_BK_COORDINATES = (TXT_TEMP_BK_COORDINATES[0], EFFICIENCY_Y)
TXT_EFFICIENCY_HLT_COORDINATES = (TXT_TEMP_HLT_COORDINATES[0], EFFICIENCY_Y)

# Selection Text Coordinates
BK_HLT_SELECTED_Y = 136
TXT_BK_SELECTED_COORDINATES = (683, BK_HLT_SELECTED_Y)
TXT_HLT_SELECTED_COORDINATES = (1528, BK_HLT_SELECTED_Y)
PUMP_SELECTED_Y = 851
TXT_P1_SELECTED_COORDINATES = (903, PUMP_SELECTED_Y)
TXT_P2_SELECTED_COORDINATES = (1552, PUMP_SELECTED_Y)
REG_SELECTED_Y = 307
TXT_REGBK_SELECTED_COORDINATES = (510, REG_SELECTED_Y)
TXT_REGHLT_SELECTED_COORDINATES = (1729, REG_SELECTED_Y)

# Settings Text Coordinates
TXT_SETTINGS_COLUMN_1_X = 700
TXT_SETTINGS_ROW_1_Y = 130
TXT_SETTINGS_Y_SPACING = 50
TXT_SETTINGS_1_COORDINATES = (TXT_SETTINGS_COLUMN_1_X, TXT_SETTINGS_ROW_1_Y)
TXT_SETTINGS_2_COORDINATES = (TXT_SETTINGS_COLUMN_1_X, TXT_SETTINGS_ROW_1_Y + TXT_SETTINGS_Y_SPACING * 1)
TXT_SETTINGS_2_COORDINATES = (TXT_SETTINGS_COLUMN_1_X, TXT_SETTINGS_ROW_1_Y + TXT_SETTINGS_Y_SPACING * 2)

# Font Sizes
TXT_TITLE_SIZE = 25
TXT_SIDEBAR_TEXT_SIZE = 20
TXT_POT_NAMES_SIZE = 32
TXT_SLIDER_VALUE_SIZE = 25
TXT_SLIDER_MINMAX_SIZE = 25
TXT_SLIDER_PLUSMINUS = 20
TXT_REG_SIZE = 20
TXT_REG_VALUE_SIZE = 25
TXT_POT_TEMPERATURES_SIZE = 50
TXT_POT_EFFICIENCY_SIZE = 25
TXT_PUMP_SPEED_SIZE = 40
TXT_EXIT_SIZE = 20
TXT_SETTINGS_SIZE = 20

# IMG GUI Coordinates
IMG_DROPSHADOWS_COORDINATES = (-15, -70)
IMG_SIDEBAR_ICONS_X = 43
IMG_SIDEBAR_ICON_HOME = (IMG_SIDEBAR_ICONS_X , 113)
IMG_SIDEBAR_ICON_GRAPHS = (IMG_SIDEBAR_ICON_HOME[0], 113 + SIDEBAR_BUTTON_DISTANCE)
IMG_SIDEBAR_ICON_SETTINGS = (IMG_SIDEBAR_ICON_HOME[0], 113 + SIDEBAR_BUTTON_DISTANCE*2)

IMG_SIDEBAR_GRAPHS_BUTTON = (0, 89+ SIDEBAR_BUTTON_DISTANCE)

IMG_KONFUS_LOGO = (102, 605)
IMG_VOICELINES = (135, 484)

IMG_POT_BK_COORDINATES = (598, 209)
IMG_POT_MLT_COORDINATES = (1037, 209)
IMG_POT_HLT_COORDINATES = (1466, 209)
IMG_PIPES_COORDINATES = (723, 264)
IMG_REG_BOX_BK_COORDINATES = (498, 354)
IMG_REG_BOX_HLT_COORDINATES = (1716, 354)
IMG_COIL_COORDINATES = (1466, 366)
IMG_HEATING_ELEMENT_BK_COORDINATES = (600, 509)
IMG_HEATING_ELEMENT_HLT_COORDINATES = (1470, 509)
IMG_PUMP_BOX_P1_COORDINATES = (854, 736)
IMG_PUMP_BOX_P2_COORDINATES = (1503, 736)
IMG_POT_BK_SELECTION_COORDINATES = (585, 195)
IMG_POT_HLT_SELECTION_COORDINATES = (1452, 195)
IMG_P1_SELECTION_COORDINATES = (840, 723)
IMG_P2_SELECTION_COORDINATES = (1490, 723)

IMG_LEGEND_X = 1800
IMG_LEGEND_Y_OFFSET = 40
IMG_LEGEND_BK_COORDINATES = (IMG_LEGEND_X,20)
IMG_LEGEND_MLT_COORDINATES = (IMG_LEGEND_X,IMG_LEGEND_BK_COORDINATES[1]+IMG_LEGEND_Y_OFFSET)
IMG_LEGEND_HLT_COORDINATES = (IMG_LEGEND_X,IMG_LEGEND_BK_COORDINATES[1]+IMG_LEGEND_Y_OFFSET*2)

IMG_SETTINGS_SCREEN_STATIC_TEXT_COORDINATES = (504, 1334-1280)

# Button Sizes
BTN_POT_ON_OFF = (251, 355)
BTN_PUMP_ON_OFF = (182, 99)
BTN_REG_MARGIN = 15
BTN_REG_ON_OFF = (105+BTN_REG_MARGIN, 69+(BTN_REG_MARGIN*2))
BTN_SIDEBAR_MENU = (399, 100)
BTN_SLIDER_SET_MINMAX = (100, 50)
BTN_QUIT = (100, 50)
BTN_GRAPH_TOGGLE_VISIBILITY_SIZE = (120,40)

BTN_GRAPH_ZOOM_SIZE = (100, 100)

# Button Coordinates
BTN_REG_ON_OFF_BK_COORDINATES = (IMG_REG_BOX_BK_COORDINATES[0] - BTN_REG_MARGIN, IMG_REG_BOX_BK_COORDINATES[1] - BTN_REG_MARGIN)
BTN_REG_ON_OFF_HLT_COORDINATES = (IMG_REG_BOX_HLT_COORDINATES[0], IMG_REG_BOX_HLT_COORDINATES[1] - BTN_REG_MARGIN)
BTN_SLIDER_SET_MINMAX_Y = 970
BTN_SLIDER_SET_MIN_COORDINATES = (560, BTN_SLIDER_SET_MINMAX_Y)
BTN_SLIDER_SET_MAX_COORDINATES = (1660, BTN_SLIDER_SET_MINMAX_Y)

BTN_SIDEBAR_ACTIVE_BUTTON_COORDINATES = (0, 89)
BTN_SIDEBAR_ACTIVE_BUTTON_GRAPHS_COORDINATES = (0, BTN_SIDEBAR_ACTIVE_BUTTON_COORDINATES[1] + SIDEBAR_BUTTON_DISTANCE)
BTN_SIDEBAR_ACTIVE_BUTTON_SETTINGS_COORDINATES = (0, BTN_SIDEBAR_ACTIVE_BUTTON_GRAPHS_COORDINATES[1] + SIDEBAR_BUTTON_DISTANCE)

BTN_QUIT_COORDINATES = (TXT_EXIT_COORDINATES[0] - 45, TXT_EXIT_COORDINATES[1] - 22)

BTN_GRAPH_Y_ZOOM_X = 550
BTN_GRAPH_Y_ZOOM_IN_COORDINATES = (BTN_GRAPH_Y_ZOOM_X, 35)
BTN_GRAPH_Y_ZOOM_OUT_COORDINATES = (BTN_GRAPH_Y_ZOOM_X, BTN_GRAPH_Y_ZOOM_IN_COORDINATES[1]+100)

BTN_GRAPH_X_ZOOM_Y = 825
BTN_GRAPH_X_ZOOM_OUT_COORDINATES = (1685, BTN_GRAPH_X_ZOOM_Y)
BTN_GRAPH_X_ZOOM_IN_COORDINATES = (BTN_GRAPH_X_ZOOM_OUT_COORDINATES[0]+100, BTN_GRAPH_X_ZOOM_Y)

BTN_GRAPH_ZOOM_AUTO_COORDINATES = (BTN_GRAPH_Y_ZOOM_X, BTN_GRAPH_X_ZOOM_Y)

BTN_GRAPH_TOGGLE_VISIBILITY_COORDINATES_X = 1790
BTN_GRAPH_TOGGLE_BK_VISIBILITY_COORDINATES = (BTN_GRAPH_TOGGLE_VISIBILITY_COORDINATES_X,18)
BTN_GRAPH_TOGGLE_MLT_VISIBILITY_COORDINATES = (BTN_GRAPH_TOGGLE_VISIBILITY_COORDINATES_X,BTN_GRAPH_TOGGLE_BK_VISIBILITY_COORDINATES[1]+40)
BTN_GRAPH_TOGGLE_HLT_VISIBILITY_COORDINATES = (BTN_GRAPH_TOGGLE_VISIBILITY_COORDINATES_X,BTN_GRAPH_TOGGLE_MLT_VISIBILITY_COORDINATES[1]+40)

# Pot on foreground original height
POT_ON_FOREGROUND_HEIGHT = 355


# Font colours
TXT_EXIT_COLOUR = '#3E3E3F'

